import { Product, Category, Enquiry } from "./types";

export const mockCategories: Category[] = [
  { id: "1", name: "Helm & Pelindung", slug: "helm-pelindung", icon: "Shield", sort_order: 1 },
  { id: "2", name: "Jersey Kustom", slug: "jersey-kustom", icon: "Shirt", sort_order: 2 },
  { id: "3", name: "Base Layer & Kaos Kaki", slug: "base-layer", icon: "Layers", sort_order: 3 },
  { id: "4", name: "Stik & Blade", slug: "stik-blade", icon: "Swords", sort_order: 4 },
  { id: "5", name: "Skate & Aksesoris", slug: "skate-aksesoris", icon: "Footprints", sort_order: 5 },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Bauer RE-AKT 85 Helmet",
    brand: "Bauer",
    category_id: "1",
    description:
      "Helm hoki es premium dengan teknologi perlindungan terdepan. Dilengkapi dengan sistem ventilasi canggih dan padding yang dapat disesuaikan untuk kenyamanan maksimal di atas es.",
    specs: {
      Bahan: "Polycarbonate Shell",
      Ukuran: "S, M, L, XL",
      Berat: "380g",
      Sertifikasi: "CSA, HECC, CE",
    },
    images: ["/products/helmet-1.jpg"],
    status: "active",
    tags: ["Pro Level", "CSA Certified"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "2",
    name: "CCM Tacks AS-V Pro Gloves",
    brand: "CCM",
    category_id: "1",
    description:
      "Sarung tangan hoki es profesional dengan konstruksi D3O® untuk perlindungan superior. Jari-jari fleksibel memberikan kontrol stik yang presisi.",
    specs: {
      Bahan: "D3O® Smart Material",
      Ukuran: "10\", 11\", 12\", 13\", 14\"",
      Berat: "280g",
      Sertifikasi: "Pro Grade",
    },
    images: ["/products/gloves-1.jpg"],
    status: "active",
    tags: ["Pro Level"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "3",
    name: "Bauer Supreme M5 Pro Skates",
    brand: "Bauer",
    category_id: "5",
    description:
      "Sepatu es performa tinggi dengan boot karbon komposit untuk dukungan dan transfer energi optimal. Blade Tuuk LS Pulse TI untuk ketajaman dan kecepatan.",
    specs: {
      Bahan: "Carbon Composite Boot",
      Ukuran: "6-12 (Fit 1, 2, 3)",
      Berat: "780g",
      Sertifikasi: "Pro Grade",
    },
    images: ["/products/skates-1.jpg"],
    status: "active",
    tags: ["Pro Level", "Best Seller"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "4",
    name: "CCM Jetspeed FT6 Pro Stick",
    brand: "CCM",
    category_id: "4",
    description:
      "Stik hoki es ringan dengan teknologi Nanolite Carbon untuk kekuatan dan responsivitas. Blade Sigmatex untuk akurasi tembakan yang konsisten.",
    specs: {
      Bahan: "Nanolite Carbon Layup",
      Ukuran: "Senior 75/85/95 Flex",
      Berat: "375g",
      Sertifikasi: "Pro Grade",
    },
    images: ["/products/stick-1.jpg"],
    status: "active",
    tags: ["Pro Level", "Lightweight"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "5",
    name: "MMJ Athletics Custom Team Jersey",
    brand: "MMJ Athletics",
    category_id: "2",
    description:
      "Jersey tim kustom dengan sublimasi penuh. Desain sesuai identitas tim Anda — nama, nomor, dan patch kapten. Bahan breathable untuk performa optimal.",
    specs: {
      Bahan: "Polyester Mesh Breathable",
      Ukuran: "Youth S - Adult 3XL",
      Berat: "220g",
      Sertifikasi: "Custom Made",
    },
    images: ["/products/jersey-1.jpg"],
    status: "active",
    tags: ["Custom", "Team Order"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "6",
    name: "Bauer Pro Series Base Layer Top",
    brand: "Bauer",
    category_id: "3",
    description:
      "Base layer kompresi dengan teknologi kelembapan untuk menjaga tubuh tetap kering dan nyaman. Pas ketat untuk performa atletik.",
    specs: {
      Bahan: "87% Polyester, 13% Spandex",
      Ukuran: "S, M, L, XL, XXL",
      Berat: "160g",
      Sertifikasi: "Performance Wear",
    },
    images: ["/products/baselayer-1.jpg"],
    status: "active",
    tags: ["Comfort Fit"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "7",
    name: "CCM Super Tacks AS4 Shoulder Pads",
    brand: "CCM",
    category_id: "1",
    description:
      "Pelindung bahu dengan konstruksi D3O® untuk perlindungan benturan maksimal. Desain ergonomis memungkinkan gerakan bebas.",
    specs: {
      Bahan: "D3O® + PE Foam",
      Ukuran: "S, M, L, XL",
      Berat: "1.2kg",
      Sertifikasi: "Pro Grade",
    },
    images: ["/products/pads-1.jpg"],
    status: "active",
    tags: ["Pro Level", "Max Protection"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: "8",
    name: "Bauer Performance Hockey Socks",
    brand: "Bauer",
    category_id: "3",
    description:
      "Kaos kaki hoki es performa tinggi dengan bantalan di area kunci. Bahan anti-bakteri menjaga kaki tetap segar selama permainan.",
    specs: {
      Bahan: "Nylon Blend Anti-Microbial",
      Ukuran: "Junior, Senior",
      Berat: "80g",
      Sertifikasi: "Performance Wear",
    },
    images: ["/products/socks-1.jpg"],
    status: "active",
    tags: ["Essential"],
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: "1",
    contact_name: "Andi Pratama",
    wa_number: "6281234567890",
    type: "equipment",
    product_id: "1",
    message: "Mau tanya stok helm Bauer RE-AKT 85 ukuran L",
    status: "new",
    pic: null,
    notes: null,
    created_at: "2025-03-28T10:00:00Z",
    updated_at: "2025-03-28T10:00:00Z",
  },
  {
    id: "2",
    contact_name: "Budi Santoso",
    wa_number: "6289876543210",
    type: "jersey",
    product_id: null,
    message: "Mau order jersey untuk tim Jakarta Ice Bears, 20 set",
    status: "replied",
    pic: null,
    notes: "Sudah kirim katalog warna",
    created_at: "2025-03-27T14:30:00Z",
    updated_at: "2025-03-28T09:00:00Z",
  },
  {
    id: "3",
    contact_name: "Diana Wijaya",
    wa_number: "6281122334455",
    type: "team",
    product_id: null,
    message: "Butuh paket lengkap untuk tim baru, 15 orang",
    status: "quoted",
    pic: null,
    notes: "Sudah kirim penawaran 45jt",
    created_at: "2025-03-25T08:00:00Z",
    updated_at: "2025-03-27T16:00:00Z",
  },
  {
    id: "4",
    contact_name: "Reza Mahendra",
    wa_number: "6287766554433",
    type: "equipment",
    product_id: "3",
    message: "Cari Bauer Supreme M5 Pro ukuran 9, Fit 2",
    status: "won",
    pic: null,
    notes: "Deal, sudah bayar",
    created_at: "2025-03-20T11:00:00Z",
    updated_at: "2025-03-22T15:00:00Z",
  },
  {
    id: "5",
    contact_name: "Siti Nurhaliza",
    wa_number: "6285544332211",
    type: "jersey",
    product_id: null,
    message: "Tanya harga jersey untuk 10 set saja bisa?",
    status: "lost",
    pic: null,
    notes: "Minimum 15 set, tidak jadi",
    created_at: "2025-03-18T09:00:00Z",
    updated_at: "2025-03-19T10:00:00Z",
  },
];
